test json taskSchedule

diff --git a/.github/workflows/auto-deployment.yml b/.github/workflows/auto-deployment.yml
--- a/.github/workflows/auto-deployment.yml
+++ b/.github/workflows/auto-deployment.yml
@@ -111,148 +111,143 @@ jobs:
             exit 1
           }
 
-      - name: 📥 Export JSON with BCP
+      - name: 📥 Save ScheduleTaskManager to JSON with BCP
         shell: pwsh
         run: |
-            $jsonFile = Join-Path $env:GITHUB_WORKSPACE "ScheduleTaskManager.json"
-            Write-Output "Exporting ScheduleTaskManager to JSON..."
-            bcp "SELECT * FROM ScheduleTaskManager FOR JSON AUTO" queryout "$jsonFile" -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -c
-        
+          $jsonFile = Join-Path $env:GITHUB_WORKSPACE "ScheduleTaskManager.json"
+          Write-Output "Exporting ScheduleTaskManager to JSON..."
+          bcp "SELECT * FROM ScheduleTaskManager FOR JSON AUTO" queryout "$jsonFile" -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -c
+
+          $jsonContent = Get-Content -Path $jsonFile -Raw
+          "SCHEDULE_TASKS_JSON=$jsonContent" | Out-File -FilePath $env:GITHUB_ENV -Append
+
       - name: 🛠️ Deactivate Tasks
         shell: pwsh
         run: |
-            Write-Output "Deactivating tasks in ScheduleTaskManager..."
-            $updateQuery = "UPDATE ScheduleTaskManager SET Active = 0"
-            $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery
-            
-            if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                Write-Error "❌ Error deactivating tasks: $updateOutput"
-                exit 1
+              Write-Output "Deactivating tasks in ScheduleTaskManager..."
+              $updateQuery = "UPDATE ScheduleTaskManager SET Active = 0"
+              $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery
+              
+              if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                  Write-Error "❌ Error deactivating tasks: $updateOutput"
+                  exit 1
+              }
+              Write-Output "✅ Tasks deactivated successfully"
+
+      - name: 🏃‍♂️‍➡️ Execute SQL scripts in the Auto_opsDataStore database
+        shell: pwsh
+        run: |
+          $folders = Get-ChildItem -Path $env:PATH_RELEASE_IODS -Recurse -Directory | Sort-Object FullName
+
+          foreach ($folder in $folders) {
+            if ($folder.Name -notmatch '^\d') {
+              Write-Output "Skipping folder (no number in name): $($folder.FullName)"
+              continue
             }
-            Write-Output "✅ Tasks deactivated successfully"
-        
-      - name: 📤 Upload JSON as artifact
-        uses: actions/upload-artifact@v4
-        with:
-            name: schedule-task-manager-json
-            path: ${{ github.workspace }}/ScheduleTaskManager.json
-        
-        
+            Write-Output "Processing folder: $($folder.FullName)"
+            $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
 
-      # - name: 🏃‍♂️‍➡️ Execute SQL scripts in the Auto_opsDataStore database
-      #   shell: pwsh
-      #   run: |
-      #     $folders = Get-ChildItem -Path $env:PATH_RELEASE_IODS -Recurse -Directory | Sort-Object FullName
+            foreach ($file in $sqlFiles) {            
+              try {
+                Write-Output "Executing $($file.FullName)..."
+                $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -i $file.FullName 2>&1
+                Write-Output "Result of $($file.Name):"
+                if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                  Write-Output "❗Error executing $($file.Name): $output"
+                } 
+                else {
+                  Write-Output "✅ Successfully executed $($file.Name)"
+                }
+              } catch {
+                Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
+              }
+            }
+          }
 
-      #     foreach ($folder in $folders) {
-      #       if ($folder.Name -notmatch '^\d') {
-      #         Write-Output "Skipping folder (no number in name): $($folder.FullName)"
-      #         continue
-      #       }
-      #       Write-Output "Processing folder: $($folder.FullName)"
-      #       $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
+      - name: 🏃‍♂️‍➡️ Execute SQL scripts in the GBDB database
+        shell: pwsh
+        run: |
+          $folders = Get-ChildItem -Path $env:PATH_RELEASE_PROFICY -Recurse -Directory | Sort-Object FullName
 
-      #       foreach ($file in $sqlFiles) {            
-      #         try {
-      #           Write-Output "Executing $($file.FullName)..."
-      #           $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -i $file.FullName 2>&1
-      #           Write-Output "Result of $($file.Name):"
-      #           if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-      #             Write-Output "❗Error executing $($file.Name): $output"
-      #           } 
-      #           else {
-      #             Write-Output "✅ Successfully executed $($file.Name)"
-      #           }
-      #         } catch {
-      #           Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
-      #         }
-      #       }
-      #     }
+          foreach ($folder in $folders) {
+            if ($folder.Name -notmatch '^\d') {
+              Write-Output "Skipping folder (no number in name): $($folder.FullName)"
+              continue
+            }
+            Write-Output "Processing folder: $($folder.FullName)"
+            $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
 
-      # - name: 🏃‍♂️‍➡️ Execute SQL scripts in the GBDB database
-      #   shell: pwsh
-      #   run: |
-      #     $folders = Get-ChildItem -Path $env:PATH_RELEASE_PROFICY -Recurse -Directory | Sort-Object FullName
+            foreach ($file in $sqlFiles) {            
+              try {
+                Write-Output "Executing $($file.FullName)..."
+                $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_PROFICY -i $file.FullName 2>&1
+                Write-Output "Result of $($file.Name):"
+                if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                  Write-Output "❗Error executing $($file.Name): $output"
+                } 
+                else {
+                  Write-Output "✅ Successfully executed $($file.Name)"
+                }
+              } catch {
+                Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
+              }
+            }
+          }
 
-      #     foreach ($folder in $folders) {
-      #       if ($folder.Name -notmatch '^\d') {
-      #         Write-Output "Skipping folder (no number in name): $($folder.FullName)"
-      #         continue
-      #       }
-      #       Write-Output "Processing folder: $($folder.FullName)"
-      #       $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
+      - name: 🔄 Update Active Status in ScheduleTaskManager
+        shell: pwsh
+        run: |
+          try {
+              Write-Output "📥 Reading JSON from environment variable..."
 
-      #       foreach ($file in $sqlFiles) {            
-      #         try {
-      #           Write-Output "Executing $($file.FullName)..."
-      #           $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_PROFICY -i $file.FullName 2>&1
-      #           Write-Output "Result of $($file.Name):"
-      #           if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-      #             Write-Output "❗Error executing $($file.Name): $output"
-      #           } 
-      #           else {
-      #             Write-Output "✅ Successfully executed $($file.Name)"
-      #           }
-      #         } catch {
-      #           Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
-      #         }
-      #       }
-      #     }
+              Write-Output "Raw JSON content: $env:SCHEDULE_TASKS_JSON"
 
-      # - name: 🔄 Update Active Status in ScheduleTaskManager
-      #   shell: pwsh
-      #   run: |
-      #     try {
-      #         Write-Output "📥 Reading JSON from environment variable..."
+              # Get the JSON from the environment variable
+              $jsonContentRaw = $env:SCHEDULE_TASKS_JSON
+              Write-Output "Raw JSON length: $($jsonContentRaw.Length)"
 
-      #         Write-Output "Raw JSON content: $env:SCHEDULE_TASKS_JSON"
+              # Convert the JSON into a PowerShell object array
+              $tasks = $jsonContentRaw | ConvertFrom-Json
 
-      #         # Get the JSON from the environment variable
-      #         $jsonContentRaw = $env:SCHEDULE_TASKS_JSON
-      #         Write-Output "Raw JSON length: $($jsonContentRaw.Length)"
+              # Check if there are tasks in the JSON
+              if (-not $tasks) {
+                  Write-Output "⚠️ No tasks found in JSON."
+                  exit 0
+              }
 
-      #         # Convert the JSON into a PowerShell object array
-      #         $tasks = $jsonContentRaw | ConvertFrom-Json
+              # Iterate through each JSON object and execute the UPDATE query
+              foreach ($task in $tasks) {
+                  $id = $task.Id
+                  $active = [int]$task.Active  # Convert boolean to 0 or 1
 
-      #         # Check if there are tasks in the JSON
-      #         if (-not $tasks) {
-      #             Write-Output "⚠️ No tasks found in JSON."
-      #             exit 0
-      #         }
+                  Write-Output "🔄 Updating ScheduleTaskManager: Id=$id, Active=$active"
 
-      #         # Iterate through each JSON object and execute the UPDATE query
-      #         foreach ($task in $tasks) {
-      #             $id = $task.Id
-      #             $active = [int]$task.Active  # Convert boolean to 0 or 1
+                  $updateQuery = "UPDATE ScheduleTaskManager SET Active = $active WHERE Id = $id"
 
-      #             Write-Output "🔄 Updating ScheduleTaskManager: Id=$id, Active=$active"
+                  # Execute the SQL query
+                  $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery -h -1 -W
 
-      #             $updateQuery = "UPDATE ScheduleTaskManager SET Active = $active WHERE Id = $id"
+                  # Check for errors in the SQL execution
+                  if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                      Write-Error "❌ Error updating Id=" + $id + ": " + $updateOutput
+                      exit 1
+                  }
+              }
 
-      #             # Execute the SQL query
-      #             $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery -h -1 -W
+              Write-Output "✅ All tasks updated successfully."
 
-      #             # Check for errors in the SQL execution
-      #             if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-      #                 Write-Error "❌ Error updating Id=" + $id + ": " + $updateOutput
-      #                 exit 1
-      #             }
-      #         }
+          } catch {
+              Write-Error "❌ Failed to update ScheduleTaskManager: $($_.Exception.Message)"
+              exit 1
+          }
 
-      #         Write-Output "✅ All tasks updated successfully."
+  api-deployment:
+    runs-on: windows-latest
+    needs: database-deployment
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
 
-      #     } catch {
-      #         Write-Error "❌ Failed to update ScheduleTaskManager: $($_.Exception.Message)"
-      #         exit 1
-      #     }
-
-  # api-deployment:
-  #   runs-on: windows-latest
-  #   needs: database-deployment
-  #   steps:
-  #     - name: Checkout repo
-  #       uses: actions/checkout@v3
-
-  #     - name: Deploy API to IIS
-  #       run: |
-  #         echo "Desplegando API en IIS..."
+      - name: Deploy API to IIS
+        run: |
+          echo "Desplegando API en IIS..."
