Update auto-deployment.yml

diff --git a/.github/workflows/auto-deployment.yml b/.github/workflows/auto-deployment.yml
--- a/.github/workflows/auto-deployment.yml
+++ b/.github/workflows/auto-deployment.yml
@@ -2,7 +2,7 @@ name: iods-auto-deploy
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   workflow_dispatch:
 
 jobs:
@@ -28,7 +28,7 @@ jobs:
         run: |
           # read JSON file
           $config = Get-Content -Raw -Path "config.json" | ConvertFrom-Json
-          
+
           # Check JSON file
           Write-Output "Config Loaded: $($config | ConvertTo-Json -Depth 3)"
 
@@ -58,8 +58,8 @@ jobs:
           Write-Output "SQL_DATABASE_IODS: $env:SQL_DATABASE_IODS"
           Write-Output "PATH_RELEASE_IODS: $env:PATH_RELEASE_IODS"  
           Write-Output "SQL_DATABASE_PROFICY: $env:SQL_DATABASE_PROFICY"
-          Write-Output "PATH_RELEASE_PROFICY: $env:PATH_RELEASE_PROFICY"     
-              
+          Write-Output "PATH_RELEASE_PROFICY: $env:PATH_RELEASE_PROFICY"
+
       - name: 🛠️ Install SQL Server tools
         run: choco install sqlcmd
 
@@ -70,7 +70,7 @@ jobs:
             Write-Output "Checking database connection..."
             $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -Q "SELECT 1" 2>&1
             if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-              Write-Error "❌ Database connection failed: $output"
+              Write-Error "❌ database connection failed: $output"
               exit 1
             }
             Write-Output "✅ Database connection successful"
@@ -78,204 +78,203 @@ jobs:
             Write-Error "❌ Failed to check database connection: $($_.Exception.Message)"
             exit 1
           }
-        
+
       - name: 🔌Check Auto_opsDataStore Database Connection
         shell: pwsh
         run: |
-            try {
-              Write-Output "Checking Auto_opsDataStore database connection..."
-              $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q "SELECT 1" 2>&1
-              if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                Write-Output "❗Database connection failed: $output"
-                exit 1
-              }
-              Write-Output "✅ Auto_opsDataStore Database connection successful"
-            } catch {
-              Write-Output "❗Failed to check Auto_opsDataStore database connection: $($_.Exception.Message)"
+          try {
+            Write-Output "Checking Auto_opsDataStore database connection..."
+            $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q "SELECT 1" 2>&1
+            if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+              Write-Output "❗Database connection failed: $output"
               exit 1
             }
-        
+            Write-Output "✅ Auto_opsDataStore Database connection successful"
+          } catch {
+            Write-Output "❗Failed to check Auto_opsDataStore database connection: $($_.Exception.Message)"
+            exit 1
+          }
+
       - name: 🔌Check GBDB Database Connection
         shell: pwsh
         run: |
-            try {
-              Write-Output "Checking GBDB database connection..."
-              $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_PROFICY -Q "SELECT 1" 2>&1
-              if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                Write-Output "❗Database connection failed: $output"
-                exit 1
-              }
-              Write-Output "✅ GBDB Database connection successful"
-            } catch {
-              Write-Output "❗Failed to check GBDB database connection: $($_.Exception.Message)"
+          try {
+            Write-Output "Checking GBDB database connection..."
+            $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_PROFICY -Q "SELECT 1" 2>&1
+            if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+              Write-Output "❗Database connection failed: $output"
               exit 1
             }
-                  
+            Write-Output "✅ GBDB Database connection successful"
+          } catch {
+            Write-Output "❗Failed to check GBDB database connection: $($_.Exception.Message)"
+            exit 1
+          }
+
       - name: 📥 Save ScheduleTaskManager to JSON and Deactivate Tasks
         shell: pwsh
         run: |
-              try {
-                    Write-Output "Fetching data from ScheduleTaskManager..."
-                  
-                    # Define the path for the JSON file
-                    $jsonFile = Join-Path $PWD "ScheduleTaskManager.json"
-                  
-                    # Execute the SELECT query and convert the result to JSON
-                    $query = "SELECT * FROM ScheduleTaskManager FOR JSON AUTO"
-                    $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $query -h -1 -W | Where-Object { $_ -notmatch 'rows affected' }
+          try {
+                Write-Output "Fetching data from ScheduleTaskManager..."
+              
+                # Define the path for the JSON file
+                $jsonFile = Join-Path $PWD "ScheduleTaskManager.json"
+              
+                # Execute the SELECT query and convert the result to JSON
+                $query = "SELECT * FROM ScheduleTaskManager FOR JSON AUTO"
+                $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $query -h -1 -W | Where-Object { $_ -notmatch 'rows affected' }
 
-                    # Check for errors in the SQL query execution
-                    if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                        Write-Error "❌ Error fetching data: $output"
-                        exit 1
-                    }
-
-                    # Convert output to JSON format
-                    $jsonContentRaw = $output -join "`n"
-
-                    # Save the output to a JSON file
-                    $jsonContentRaw | Out-File -Encoding utf8 $jsonFile
-                    Write-Output "✅ Data exported successfully to $jsonFile"
-
-                    # Save the JSON content in a GitHub Actions environment variable
-                    "SCHEDULE_TASKS_JSON=$jsonContentRaw" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-
-                    # Print confirmation message
-                    Write-Output "📂 JSON stored in GitHub Actions environment variable: SCHEDULE_TASKS_JSON"
-                                
-                    # Execute the UPDATE query to set Active column to 0 (deactivate tasks)
-                    Write-Output "Deactivating tasks by updating Active column to 0..."
-                    $updateQuery = "UPDATE ScheduleTaskManager SET Active = 0"
-                    $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery
-                  
-                    # Check for errors in the update execution
-                    if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                        Write-Error "❌ Error deactivating tasks: $updateOutput"
-                        exit 1
-                    }             
-                    Write-Output "✅ Tasks deactivated successfully"
-                } 
-                catch {
-                    # Handle any unexpected errors
-                    Write-Error "❌ Failed to process ScheduleTaskManager: $($_.Exception.Message)"
+                # Check for errors in the SQL query execution
+                if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                    Write-Error "❌ Error fetching data: $output"
                     exit 1
                 }
-    
+
+                # Convert output to JSON format
+                $jsonContentRaw = $output -join "`n"
+
+                # Save the output to a JSON file
+                $jsonContentRaw | Out-File -Encoding utf8 $jsonFile
+                Write-Output "✅ Data exported successfully to $jsonFile"
+
+                # Save the JSON content in a GitHub Actions environment variable
+                "SCHEDULE_TASKS_JSON=$jsonContentRaw" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+
+                # Print confirmation message
+                Write-Output "📂 JSON stored in GitHub Actions environment variable: SCHEDULE_TASKS_JSON"
+                            
+                # Execute the UPDATE query to set Active column to 0 (deactivate tasks)
+                Write-Output "Deactivating tasks by updating Active column to 0..."
+                $updateQuery = "UPDATE ScheduleTaskManager SET Active = 0"
+                $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery
+              
+                # Check for errors in the update execution
+                if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                    Write-Error "❌ Error deactivating tasks: $updateOutput"
+                    exit 1
+                }             
+                Write-Output "✅ Tasks deactivated successfully"
+            } 
+            catch {
+                # Handle any unexpected errors
+                Write-Error "❌ Failed to process ScheduleTaskManager: $($_.Exception.Message)"
+                exit 1
+            }
+
       - name: 🏃‍♂️‍➡️ Execute SQL scripts in the Auto_opsDataStore database
         shell: pwsh
-        run: |     
-            $folders = Get-ChildItem -Path $env:PATH_RELEASE_IODS -Recurse -Directory | Sort-Object FullName
-            
-            foreach ($folder in $folders) {
-              if ($folder.Name -notmatch '^\d') {
-                Write-Output "Skipping folder (no number in name): $($folder.FullName)"
-                continue
-              }
-              Write-Output "Processing folder: $($folder.FullName)"
-              $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
-            
-              foreach ($file in $sqlFiles) {            
-                try {
-                  Write-Output "Executing $($file.FullName)..."
-                  $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -i $file.FullName 2>&1
-                  Write-Output "Result of $($file.Name):"
-                  if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                    Write-Output "❗Error executing $($file.Name): $output"
-                  } 
-                  else {
-                    Write-Output "✅ Successfully executed $($file.Name)"
-                  }
-                } catch {
-                  Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
+        run: |
+          $folders = Get-ChildItem -Path $env:PATH_RELEASE_IODS -Recurse -Directory | Sort-Object FullName
+
+          foreach ($folder in $folders) {
+            if ($folder.Name -notmatch '^\d') {
+              Write-Output "Skipping folder (no number in name): $($folder.FullName)"
+              continue
+            }
+            Write-Output "Processing folder: $($folder.FullName)"
+            $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
+
+            foreach ($file in $sqlFiles) {            
+              try {
+                Write-Output "Executing $($file.FullName)..."
+                $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -i $file.FullName 2>&1
+                Write-Output "Result of $($file.Name):"
+                if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                  Write-Output "❗Error executing $($file.Name): $output"
+                } 
+                else {
+                  Write-Output "✅ Successfully executed $($file.Name)"
                 }
+              } catch {
+                Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
               }
             }
-      
+          }
+
       - name: 🏃‍♂️‍➡️ Execute SQL scripts in the GBDB database
         shell: pwsh
-        run: |     
-                $folders = Get-ChildItem -Path $env:PATH_RELEASE_PROFICY -Recurse -Directory | Sort-Object FullName
-                
-                foreach ($folder in $folders) {
-                  if ($folder.Name -notmatch '^\d') {
-                    Write-Output "Skipping folder (no number in name): $($folder.FullName)"
-                    continue
-                  }
-                  Write-Output "Processing folder: $($folder.FullName)"
-                  $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
-                
-                  foreach ($file in $sqlFiles) {            
-                    try {
-                      Write-Output "Executing $($file.FullName)..."
-                      $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_PROFICY -i $file.FullName 2>&1
-                      Write-Output "Result of $($file.Name):"
-                      if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                        Write-Output "❗Error executing $($file.Name): $output"
-                      } 
-                      else {
-                        Write-Output "✅ Successfully executed $($file.Name)"
-                      }
-                    } catch {
-                      Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
-                    }
-                  }
+        run: |
+          $folders = Get-ChildItem -Path $env:PATH_RELEASE_PROFICY -Recurse -Directory | Sort-Object FullName
+
+          foreach ($folder in $folders) {
+            if ($folder.Name -notmatch '^\d') {
+              Write-Output "Skipping folder (no number in name): $($folder.FullName)"
+              continue
+            }
+            Write-Output "Processing folder: $($folder.FullName)"
+            $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
+
+            foreach ($file in $sqlFiles) {            
+              try {
+                Write-Output "Executing $($file.FullName)..."
+                $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_PROFICY -i $file.FullName 2>&1
+                Write-Output "Result of $($file.Name):"
+                if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                  Write-Output "❗Error executing $($file.Name): $output"
+                } 
+                else {
+                  Write-Output "✅ Successfully executed $($file.Name)"
                 }
-  
+              } catch {
+                Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
+              }
+            }
+          }
+
       - name: 🔄 Update Active Status in ScheduleTaskManager
         shell: pwsh
         run: |
-                try {
-                    Write-Output "📥 Reading JSON from environment variable..."
-               
-                    Write-Output "Raw JSON content: $env:SCHEDULE_TASKS_JSON"
-        
-                    # Get the JSON from the environment variable
-                    $jsonContentRaw = $env:SCHEDULE_TASKS_JSON
-                    Write-Output "Raw JSON length: $($jsonContentRaw.Length)"
+          try {
+              Write-Output "📥 Reading JSON from environment variable..."
 
-                    # Convert the JSON into a PowerShell object array
-                    $tasks = $jsonContentRaw | ConvertFrom-Json
-        
-                    # Check if there are tasks in the JSON
-                    if (-not $tasks) {
-                        Write-Output "⚠️ No tasks found in JSON."
-                        exit 0
-                    }
-        
-                    # Iterate through each JSON object and execute the UPDATE query
-                    foreach ($task in $tasks) {
-                        $id = $task.Id
-                        $active = [int]$task.Active  # Convert boolean to 0 or 1
-        
-                        Write-Output "🔄 Updating ScheduleTaskManager: Id=$id, Active=$active"
-        
-                        $updateQuery = "UPDATE ScheduleTaskManager SET Active = $active WHERE Id = $id"
-        
-                        # Execute the SQL query
-                        $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery -h -1 -W
-        
-                        # Check for errors in the SQL execution
-                        if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
-                            Write-Error "❌ Error updating Id=" + $id + ": " + $updateOutput
-                            exit 1
-                        }
-                    }
-        
-                    Write-Output "✅ All tasks updated successfully."
-        
-                } catch {
-                    Write-Error "❌ Failed to update ScheduleTaskManager: $($_.Exception.Message)"
-                    exit 1
-                }
-              
+              Write-Output "Raw JSON content: $env:SCHEDULE_TASKS_JSON"
+
+              # Get the JSON from the environment variable
+              $jsonContentRaw = $env:SCHEDULE_TASKS_JSON
+              Write-Output "Raw JSON length: $($jsonContentRaw.Length)"
+
+              # Convert the JSON into a PowerShell object array
+              $tasks = $jsonContentRaw | ConvertFrom-Json
+
+              # Check if there are tasks in the JSON
+              if (-not $tasks) {
+                  Write-Output "⚠️ No tasks found in JSON."
+                  exit 0
+              }
+
+              # Iterate through each JSON object and execute the UPDATE query
+              foreach ($task in $tasks) {
+                  $id = $task.Id
+                  $active = [int]$task.Active  # Convert boolean to 0 or 1
+
+                  Write-Output "🔄 Updating ScheduleTaskManager: Id=$id, Active=$active"
+
+                  $updateQuery = "UPDATE ScheduleTaskManager SET Active = $active WHERE Id = $id"
+
+                  # Execute the SQL query
+                  $updateOutput = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE_IODS -Q $updateQuery -h -1 -W
+
+                  # Check for errors in the SQL execution
+                  if ($updateOutput -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
+                      Write-Error "❌ Error updating Id=" + $id + ": " + $updateOutput
+                      exit 1
+                  }
+              }
+
+              Write-Output "✅ All tasks updated successfully."
+
+          } catch {
+              Write-Error "❌ Failed to update ScheduleTaskManager: $($_.Exception.Message)"
+              exit 1
+          }
 
   api-deployment:
     runs-on: windows-latest
-    needs: database-deployment 
+    needs: database-deployment
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
-    
+
       - name: Deploy API to IIS
         run: |
           echo "Desplegando API en IIS..."
